{{- if .Values.ingress.enabled -}}
{{- $fullName := include "catanie.fullname" . -}}
{{- $serviceName := include "catanie.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $host := .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "catanie.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - secretName: catanieservice
  {{- if eq .Release.Namespace "production"}}
    hosts:
    - scitest.esss.lu.se
  {{- else }}
    hosts:
    - scicat02.esss.lu.se
  {{- end }}
  rules:
  {{- if eq .Release.Namespace "production"}}
    - host: scitest.esss.lu.se
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- else }}
    - host: scicat02.esss.lu.se
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end -}}

