{{- if .Values.ingress.enabled -}}
{{- $fullName := include "catanie.fullname" . -}}
{{- $serviceName := include "catanie.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $host := .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "catanie.labels" . | indent 4 }}
    {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      {{ if eq .Release.Namespace "production" }}
      - scitest.esss.lu.se
      {{ else }}
      - scicat02.esss.dk
      {{ end }}
    - secretName: catanieservice
  rules:
    {{ if eq .Release.Namespace "production" }}
    - host: scitest.esss.lu.se
    {{ else }}
    - host: scicat02.esss.dk
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{- end -}}
