kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvpostgres
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/postgresql"
